//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public System.Guid Id { get; set; }
        public System.Guid BookId { get; set; }
        public Nullable<int> CreaterId { get; set; }
        public string Creater { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string IsEnable { get; set; }
        public Nullable<double> Rating { get; set; }
    }
}
